# Run using `docker-compose -f databases.yaml up`.
version: "3.1"

services:
  vaxine:
    image: europe-docker.pkg.dev/vaxine/vaxine-io/vaxine:latest
#    restart: always
    environment:
      RING_SIZE: "1"
      ANTIDOTE_TXN_CERT: "false" # disabled because we must accept all transactions
      ANTIDOTE_TXN_PROT: "clocksi"
      ANTIDOTE_RECOVER_FROM_LOG: "true"
      ANTIDOTE_META_DATA_ON_START: "true"
      ANTIDOTE_SYNC_LOG: "true"
      ANTIDOTE_ENABLE_LOGGING: "true"
      ANTIDOTE_AUTO_START_READ_SERVERS: "true"
      COOKIE: "secret"
      NODE_NAME: "antidote@dc1n1"
      DEBUG_LOGGER_LEVEL: "debug"
    ports:
      - "8087:8087"
      - "8088:8088"
    privileged: true

  db_a:
    image: europe-docker.pkg.dev/vaxine/vaxine-io/postgres:latest
#    restart: always
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - ./postgres.conf:/etc/postgresql.conf:ro
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db_b:
    image: europe-docker.pkg.dev/vaxine/vaxine-io/postgres:latest
#    restart: always
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: password
    ports:
      - "54322:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - ./postgres.conf:/etc/postgresql.conf:ro
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  auth:
    image: mockserver/mockserver:mockserver-snapshot
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /auth_mock.json
    volumes:
      - ./integration_tests/auth_mock.json:/auth_mock.json:ro
