version: '3.8'

configs:
  postgres_config:
    file: './postgres/postgres.conf'

volumes:
  pg_data:
  electric_data:

services:
  postgres:
    image: '${POSTGRESQL_IMAGE:-postgres:14-alpine}'
    environment:
      POSTGRES_DB: ${APP_NAME:-electric}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    image: '${ELECTRIC_IMAGE:-electricsql/electric:0.6.4}'
    init: true
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/${APP_NAME:-electric}
      LOGICAL_PUBLISHER_HOST: electric
      AUTH_MODE: insecure
    ports:
      - 5133:5133
    volumes:
      - electric_data:/app/data
    depends_on:
      - postgres
