version: "3.8"

configs:
  postgres_config:
    file: "./postgres/postgres.conf"
  postgres_init_sql:
    file: "./postgres/init.sql"

volumes:
  pg_data:
  electric_data:

services:
  postgres:
    image: "${POSTGRESQL_IMAGE:-postgres:14-alpine}"
    environment:
      POSTGRES_DB: ${APP_NAME:-electric}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
      - source: postgres_init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    image: "${ELECTRIC_IMAGE:-electricsql/electric:latest}"
    init: true
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/${APP_NAME:-electric}
      LOGICAL_PUBLISHER_HOST: electric
      # Currently published version (electric-sql@0.5.0-next.4)
      # still uses `ELECTRIC_HOST` variable
      # but future versions will use `LOGICAL_PUBLISHER_HOST`
      # TODO: Remove `ELECTRIC_HOST` when next version is published.
      ELECTRIC_HOST: electric
      OFFSET_STORAGE_FILE: "/app/data/offset_storage.dat"
      AUTH_MODE: insecure
    ports:
      - 5050:5050
      - 5133:5133
    volumes:
      - electric_data:/app/data
    depends_on:
      - postgres
