version: "3.8"

configs:
  postgres_config:
    file: "./postgres.conf"

volumes:
  pg_data:
  electric_data:

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "beer-stars"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 54321:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    image: electricsql/electric:latest
    init: true
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/beer-stars"
      ELECTRIC_HOST: electric
      LOGICAL_PUBLISHER_HOST: electric
      AUTH_MODE: insecure
    ports:
      - 5133:5133
      - 65432:65432
    volumes:
      - electric_data:/app/data
    depends_on:
      - postgres

  server:
    image: beer-stars/server
    build: ../server
    init: true
    environment:
      BEER_STARS_WORKER: true
      DATABASE_HOST: "postgres"
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/beer-stars"
      GITHUB_REPO: "${GITHUB_REPO:-electric-sql/electric}"
      GITHUB_TOKENS: "${GITHUB_TOKENS}"
      PHX_HOST: "localhost"
      PHX_SERVER: true
      PORT: 40001
      SECRET_KEY_BASE: "E4NrRTr/ZAPGS5Ubp0DmizfdRrRdAV1vLAC7PDQQOupVucwGTinsuEF2BlkOjBWm"
    ports:
      - 40001:40001
    depends_on:
      - postgres
