# Run using `docker-compose -f databases.yaml up`.
version: '3.7'

services:
  vaxine_1:
    extends:
      file: ../services_templates.yaml
      service: vaxine
    environment:
      NODE_NAME: "vaxine@vaxine_1"
    volumes:
      - ${VAXINE_VOLUME}/vaxine_1:/vaxine-data
    ports:
      - "8087:8087"
      - "8088:8088"

  electric_1:
    extends:
      file: ../services_templates.yaml
      service: electric
    environment:
      VAXINE_HOST: vaxine_1
      ELECTRIC_HOST: electric_1
      CONNECTORS: >-
        postgres_1=postgresql://postgres:password@pg_1:5432/electric;
        postgres_2=postgresql://postgres:password@pg_2:5432/electric;
      ELECTRIC_INSTANCE_ID: instance-a.region-1.test.electric-db
      ELECTRIC_REGIONAL_ID: region-1.test.electric-db
    ports:
      - "5050:5050"
      - "5133:5133"
    depends_on:
      - pg_1
      - pg_2
      - vaxine_1

  electric_2:
    extends:
      file: ../services_templates.yaml
      service: electric
    environment:
      VAXINE_HOST: vaxine_1
      ELECTRIC_HOST: electric_2
      CONNECTORS: >-
        postgres_3=postgresql://postgres:password@pg_3:5432/electric;
      ELECTRIC_INSTANCE_ID: instance-b.region-1.test.electric-db
      ELECTRIC_REGIONAL_ID: region-1.test.electric-db
    ports:
      - "5051:5050"
      - "5134:5133"
    depends_on:
      - pg_3
      - vaxine_1

  sysbench:
    extends:
      file: ../services_templates.yaml
      service: sysbench

  elixir_client_1:
    extends:
      file: ../services_templates.yaml
      service: elixir_client

  elixir_client_2:
    extends:
      file: ../services_templates.yaml
      service: elixir_client

  elixir_client_3:
    extends:
      file: ../services_templates.yaml
      service: elixir_client

  pg_1:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54321:5432"

  pg_2:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54322:5432"

  pg_3:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54323:5432"
