# Run using `docker-compose -f databases.yaml up`.
version: '3.1'

services:
  vaxine:
    image: "${VAXINE_IMAGE:-vaxine:local-build}"
    environment:
      RING_SIZE: "1"
      ANTIDOTE_TXN_CERT: "false" # disabled because we must accept all transactions
      ANTIDOTE_TXN_PROT: "clocksi"
      ANTIDOTE_RECOVER_FROM_LOG: "true"
      ANTIDOTE_META_DATA_ON_START: "true"
      ANTIDOTE_SYNC_LOG: "true"
      ANTIDOTE_ENABLE_LOGGING: "true"
      ANTIDOTE_AUTO_START_READ_SERVERS: "true"
      COOKIE: "secret"
      NODE_NAME: "antidote@dc1n1"
    ports:
      - "8087:8087"
      - "8088:8088"
    privileged: true

  electric:
    image: electric:local-build
    privileged: true
    volumes:
      - ./electric.exs:/app/releases/0.1.0/runtime.exs:ro
    depends_on:
      - db_a
      - db_b
      - vaxine

  electric_b:
    image: electric:local-build
    privileged: true
    # entrypoint: /bin/bash
    # stdin_open: true # docker run -i
    # tty: true
    volumes:
      - ./electric_b.exs:/app/releases/0.1.0/runtime.exs:ro
    depends_on:
      - db_c
      - vaxine

  db_a:
    image: postgres:13
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - ./postgres.conf:/etc/postgresql.conf:ro
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U electric"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db_b:
    image: postgres:13
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: password
    ports:
      - "54322:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - ./postgres.conf:/etc/postgresql.conf:ro
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U electric"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db_c:
    image: postgres:13
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: electric
      POSTGRES_PASSWORD: password
    ports:
      - "54323:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - ./postgres.conf:/etc/postgresql.conf:ro
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U electric"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

