# Run using `docker-compose -f databases.yaml up`.
version: '3.1'

services:
  vaxine_1:
    extends:
      file: ../services_templates.yaml
      service: vaxine
    environment:
      NODE_NAME: "vaxine@vaxine_1"
    volumes:
      - ${VAXINE_VOLUME}/vaxine_1:/vaxine-data
    ports:
      - "8087:8087"
      - "8088:8088"

  electric_1:
    extends:
      file: ../services_templates.yaml
      service: electric
    volumes:
      - ./electric.exs:/app/releases/0.1.0/runtime.exs:ro
      - ./migrations/:/migrations:ro
    ports:
      - "5050:5050"
      - "5133:5133"
    depends_on:
      - pg_1
      - pg_2
      - vaxine_1

  electric_2:
    extends:
      file: ../services_templates.yaml
      service: electric
    volumes:
      - ./electric_b.exs:/app/releases/0.1.0/runtime.exs:ro
      - ./migrations:/migrations:ro
    ports:
      - "5051:5050"
      - "5134:5133"
    depends_on:
      - pg_3
      - vaxine_1

  sysbench:
    extends:
      file: ../services_templates.yaml
      service: sysbench

  pg_1:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    ports:
      - "54321:5432"

  pg_2:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    ports:
      - "54322:5432"

  pg_3:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    ports:
      - "54323:5432"

  satellite_client_1:
    extends:
      file: ../services_templates.yaml
      service: satellite_client
    environment:
      MIGRATION_DIRS: ${MIGRATION_DIRS}
    volumes:
       - ${MIGRATION_DIRS}:${MIGRATION_DIRS}:ro

  satellite_client_2:
    extends:
      file: ../services_templates.yaml
      service: satellite_client
    environment:
      MIGRATION_DIRS: ${MIGRATION_DIRS}
    volumes:
       - ${MIGRATION_DIRS}:${MIGRATION_DIRS}:ro
