[dev]
  command = "pnpm dev"
  targetPort = 5173

[build.environment]
  # Environment variables are set here

  # Node version here should match the one in .tool-versions - that's the authoritative source
  NODE_VERSION = "22.12.0"

[[edge_functions]]
  function = "serve-markdown"
  path = "/*"