version: '3.8'
name: 'electric_dev_otel'

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '54321:5432'
    volumes:
      - ./postgres.conf:/etc/postgresql.conf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/00_shared_init.sql:ro
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
  electric:
    image: electricsql/electric:latest
    environment:
      ELECTRIC_INSECURE: ${ELECTRIC_INSECURE:-true}
      ELECTRIC_OTLP_ENDPOINT: http://otel:4318/
      ELECTRIC_PROMETHEUS_PORT: ${ELECTRIC_PROMETHEUS_PORT:-4000}
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
    ports:
      - 3000:3000
      - 4000:4000
  otel:
    image: otel/opentelemetry-collector-contrib:0.105.0
    environment:
      ELECTRIC_HNY_DATASET: ${ELECTRIC_HNY_DATASET}
      ELECTRIC_HNY_API_KEY: ${ELECTRIC_HNY_API_KEY}
      PROMETHEUS_SCRAPE_ENDPOINT: electric:4000
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
    ports:
      - 4317:4317
      - 4318:4318
    command: ['--config=/conf/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-honeycomb-config.yaml:/conf/otel-collector-config.yaml
  nginx:
    image: nginx:latest
    ports:
      - '3002:3002'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - electric
