version: "3.8"

x-preshared-auth-variables: &preshared-auth-variables
  AUTH_JWT_ALG: HS256
  AUTH_JWT_KEY: local-development-key-minimum-32-symbols
configs:
  postgres_config:
    file: "./compose/postgres/postgres.conf"
  postgres_init_sql:
    file: "./compose/postgres/init.sql"

volumes:
  pg_data:
  electric_data:

services:
  postgres_1:
    extends:
      file: "./compose/docker-compose-templates.yaml"
      service: postgres_template
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric_1:
    extends:
      file: "./compose/docker-compose-templates.yaml"
      service: electric_template
    environment:
      <<: *preshared-auth-variables
      DATABASE_URL: postgresql://postgres:password@postgres_1:5432/electric
      LOGICAL_PUBLISHER_HOST: electric_1
      # Currently published version (electric-sql@0.5.0-next.4)
      # still uses `ELECTRIC_HOST` variable
      # but future versions will use `LOGICAL_PUBLISHER_HOST`
      # TODO: Remove `ELECTRIC_HOST` when next version is published.
      ELECTRIC_HOST: electric_1
    ports:
      - 5050:5050
      - 5133:5133
      - 5433:5433
    volumes:
      - electric_data:/app/data
    depends_on:
      - postgres_1
