name: Docker Image for sync-service

on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
        default: ghcr.io/${{ github.repository }}/sync-service
      tag:
        required: false
        type: string
      platforms:
        required: false
        type: string
        default: linux/amd64
    outputs:
      image_ref:
        description: 'Full image ref'
        value: ${{ jobs.build_image.outputs.image_ref }}
      image:
        description: 'The repository part of the image, without the tag'
        value: ${{ jobs.build_image.outputs.image }}
      tag:
        description: 'Only the tag part'
        value: ${{ jobs.build_image.outputs.tag }}
      digest:
        description: 'The sha256 digest for the image produced by Docker builder'
        value: ${{ jobs.build_image.outputs.digest }}

jobs:
  build_image:
    runs-on: ubuntu-latest

    # Make sure that all workflows calling this with the same tag will queue here.
    # Only the first workflow to reach this point will trigger a new image build, the other
    # workflows will use it once it's been built and pushed.
    concurrency:
      group: sync-service-ci-image-${{ inputs.tag }}
      cancel-in-progress: false

    permissions:
      contents: read
      packages: write

    outputs:
      image_ref: ${{ steps.out.outputs.image_ref }}
      image: ${{ steps.out.outputs.image }}
      tag: ${{ steps.out.outputs.tag }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4
        with:
          # It is crucial that we checkout the actual HEAD commit of the branch instead of
          # GitHub's ephemeral merge commit that it creates for CI runs by default.
          # We rely on the correct HEAD commit to be checked out in order to determine the
          # correct ELECTRIC_VERSION to bake into the Docker image.
          ref: ${{ github.event.pull_request.head.sha }}
          # Also important to fetch the whole history since otherwise we won't get that tags
          # that are required to determine the correct ELECTRIC_VERSION.
          fetch-depth: 0
          fetch-tags: true

      - name: Set image ref
        id: vars
        run: |
          echo "IMAGE=${{ inputs.image }}" >> $GITHUB_ENV
          echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV

      - name: Login to GHCR (private)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the latest commit SHA that has touched files in either packages/electric-telemetry or packages/sync-service
        if: ${{ !env.TAG }}
        run: |
          echo "TAG=$(
            git log -1 --format='%h' -- packages/electric-telemetry/ packages/sync-service/
          )" >> $GITHUB_ENV

      - name: Determine ELECTRIC_VERSION to pass as a build-arg to the builder
        run: |
          echo "ELECTRIC_VERSION=$(
            git describe --abbrev=7 --tags --always --first-parent --match '@core/sync-service@*' | sed -En 's|^@core/sync-service@||p'
          )" >> $GITHUB_ENV

      - name: Check if image tag already exists
        id: exists
        run: |
          if docker manifest inspect "${IMAGE}:${TAG}" > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - uses: docker/setup-buildx-action@v3

      - name: Build and push if missing
        if: steps.exists.outputs.exists != 'true'
        id: build
        uses: docker/build-push-action@v6
        with:
          context: packages/sync-service
          build-contexts: |
            electric-telemetry=packages/electric-telemetry
          build-args: |
            ELECTRIC_VERSION=${{ env.ELECTRIC_VERSION }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image ref
        id: out
        run: |
          echo "image_ref=${IMAGE}:${TAG}" >> $GITHUB_OUTPUT
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
